use_frameworks!

platform :ios, '12.0'

target 'BPenPlusSDK_Example' do
  pod 'BPenPlusSDK', :path => '../'

  target 'BPenPlusSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
